# Generated by Django 4.2.20 on 2025-03-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='companies.role'),
        ),
    ]
