# Generated by Django 4.2.20 on 2025-03-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=255)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_entry', to='agents.agent')),
            ],
        ),
    ]
