# Generated by Django 4.2.20 on 2025-09-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_parent_workflow'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MarketplaceWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_entry', to='workflows.workflow')),
            ],
        ),
    ]
