# Generated by Django 4.2.20 on 2025-03-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflowId', models.AutoField(primary_key=True, serialize=False)),
                ('workflowName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('agents', models.ManyToManyField(related_name='workflows', to='agents.agent')),
                ('tools', models.ManyToManyField(related_name='workflows', to='workflows.tool')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.trigger')),
            ],
        ),
    ]
