# Generated by Django 4.2.20 on 2025-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='nodes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workflow',
            name='relations',
            field=models.JSONField(default=list),
        ),
    ]
