# Generated by Django 4.2.20 on 2025-09-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_creator_workflow_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='workflows.workflow'),
        ),
    ]
