# Generated by Django 4.2.20 on 2025-03-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agentId', models.AutoField(primary_key=True, serialize=False)),
                ('agentName', models.CharField(max_length=255)),
                ('agentRole', models.CharField(max_length=100)),
                ('agentObjective', models.TextField()),
                ('agentInstructions', models.TextField()),
                ('etat', models.CharField(choices=[('draft', 'Draft'), ('deployed', 'Deployed')], max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.datasource')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.modele')),
            ],
        ),
    ]
