# Generated by Django 4.2.20 on 2025-04-28 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_creator_alter_datasource_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='etat',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('deployed', 'Déployé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('local', 'Fichier local'), ('custom_links', 'Liens personnalisés'), ('external_api', 'API externe')], default='local', max_length=100),
        ),
    ]
