# Generated by Django 4.2.20 on 2025-05-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_created_at_agent_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='link_list',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='agents.agent')),
            ],
        ),
    ]
