# Generated by Django 4.2.20 on 2025-05-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_link_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='link_list',
            new_name='links',
        ),
    ]
