# Generated by Django 4.2.20 on 2025-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_rename_description_link_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(),
        ),
    ]
