# Generated by Django 4.2.20 on 2025-07-19 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0009_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
