# Generated by Django 4.2.20 on 2025-09-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='parent_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='agents.agent'),
        ),
    ]
