# Generated by Django 4.2.20 on 2025-09-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_parent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
