# Generated by Django 4.2.20 on 2025-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agentfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agentRole',
            field=models.CharField(max_length=255),
        ),
    ]
