# Generated by Django 4.2.20 on 2025-04-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='onboarding_completed',
        ),
    ]
