# Generated by Django 4.2.20 on 2025-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='company',
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Éditeur', 'Éditeur'), ('Visiteur', 'Visiteur')], default='Éditeur', max_length=50),
            preserve_default=False,
        ),
    ]
