# Generated by Django 4.2.20 on 2025-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_invitation_company_invitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Éditeur', 'Éditeur'), ('Visiteur', 'Visiteur')], default='En cours', max_length=50),
        ),
    ]
