# Generated by Django 4.2.20 on 2025-07-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_role_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='selected_agents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invitation',
            name='selected_workflows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
